# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20170121_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teach',
            name='group',
        ),
        migrations.RemoveField(
            model_name='teach',
            name='subject',
        ),
        migrations.AddField(
            model_name='group',
            name='professor_subjects',
            field=models.ManyToManyField(to='Main.ProfessorSubject'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='Main.Student'),
        ),
        migrations.AddField(
            model_name='professor',
            name='subjects',
            field=models.ManyToManyField(through='Main.ProfessorSubject', to='Main.Subject'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='Main.Question'),
        ),
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to='Main.Student'),
        ),
        migrations.AlterField(
            model_name='professorsubject',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_subject', to='Main.Professor'),
        ),
        migrations.AlterField(
            model_name='professorsubject',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='Main.Subject'),
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='StudentGroup',
        ),
        migrations.DeleteModel(
            name='Teach',
        ),
    ]
