# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_answer_attachment_comment_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.Student'),
        ),
    ]
