# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 09:26
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20170121_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
