# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20170121_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
