# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20170121_0956'),
        ('Main', '0011_auto_20170121_0916'),
    ]

    operations = [
    ]
